### ISSUE TITLE
C-c C-d 快捷键冲突

### ISSUE THREAD

**Issue by Jack126** [cabins/emacs.d#1]
C-c C-d  python-describe-at-point , crux-duplicate-current-line-or-region两种 定义，是否快捷键冲突？

**Comment by cabins** [comment]
是的，存在快捷冲突。去掉crux的这个绑定。因为move-dup里面已经使用了C-M-<方向键>来完成这个函数类似的功能了。

**Comment by cabins** [comment]
非常感谢反馈！！
