### ISSUE TITLE
prog-mode 和 eglot-ensure关联会导致打开elisp文件时报错

### ISSUE THREAD

**Issue by mzgcz** [cabins/emacs.d#7]
https://github.com/cabins/emacs.d/blob/1bebdb984dd08ada00b4174b9fb4bd23464985a3/init.el#L239C3-L239C35

> Error in post-command-hook (#[0 "\303\301!\205\0r\301q\210\304\305\300\242\306#\210
?\205\0\307\310\311 \")\207" [(#0) #<buffer init.el> eglot--managed-mode buffer-live-p remove-hook post-command-hook t apply eglot--connect eglot--guess-contact] 4]): (wrong-type-argument processp nil)

**Comment by cabins** [comment]
是的。因为eglot处理不了lisp的类型。但，这个报错其实还好。因为它不影响使用。更优的方式是，不要使用prog-mode，而是需要哪个添加哪个。

**Comment by mzgcz** [comment]
> 是的。因为eglot处理不了lisp的类型。但，这个报错其实还好。因为它不影响使用。更优的方式是，不要使用prog-mode，而是需要哪个添加哪个。

嗯，对应安装 lsp 服务端的mode，逐个添加比较好
